# ============================================================================
# INSA-ERP — Frontend Production Multi-Stage Dockerfile
# Framework: Next.js 15 (App Router) | Node 20 LTS | Standalone Runtime
# ============================================================================

# ----------------------------------------------------------------------------
# Stage 1: Base image setup
# ----------------------------------------------------------------------------
FROM node:20-alpine AS base
WORKDIR /app
# Install libc6-compat for compatibility with native modules on alpine
RUN apk add --no-cache libc6-compat wget

# ----------------------------------------------------------------------------
# Stage 2: Install dependencies (cached layer)
# ----------------------------------------------------------------------------
FROM base AS deps
WORKDIR /app
# Copy package manifests first for optimal layer caching
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

# ----------------------------------------------------------------------------
# Stage 3: Build the application
# ----------------------------------------------------------------------------
FROM base AS builder
WORKDIR /app

# Copy installed dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
# Copy all source files
COPY . .

# Next.js telemetry opt-out during build
ENV NEXT_TELEMETRY_DISABLED 1

# Environment build arguments (passed during docker compose build)
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_AUTH_MODE
ARG NEXT_PUBLIC_MMS_API_URL
ARG KEYCLOAK_ISSUER_URI
ARG KEYCLOAK_FRONTEND_CLIENT_ID

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_AUTH_MODE=${NEXT_PUBLIC_AUTH_MODE}
ENV NEXT_PUBLIC_MMS_API_URL=${NEXT_PUBLIC_MMS_API_URL}
ENV KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
ENV KEYCLOAK_FRONTEND_CLIENT_ID=${KEYCLOAK_FRONTEND_CLIENT_ID}

# Build Next.js standalone application
RUN npm run build

# ----------------------------------------------------------------------------
# Stage 4: Lightweight Production Runtime Image
# ----------------------------------------------------------------------------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED 1
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Create unprivileged system user for security best practice
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public static assets from builder stage
COPY --from=builder /app/public ./public

# Set directory permissions for Next.js cache
RUN mkdir .next && chown nextjs:nodejs .next

# Copy standalone output & static assets generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Install wget in runner for container health check
RUN apk add --no-cache wget

# Switch to non-root user
USER nextjs

EXPOSE 3000

# Health check to ensure server is responding
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1

# Launch standalone Node.js server
CMD ["node", "server.js"]
