-- Training programs, sessions, enrollments and the certifications they produce.

CREATE TABLE hrm_schema.training_program
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    title          varchar(255)  NOT NULL,
    description    varchar(1500),
    category       varchar(255),
    provider       varchar(255),
    duration_hours integer       NOT NULL,
    start_date     date          NOT NULL,
    end_date       date          NOT NULL,
    cost           numeric(19, 4),
    status         varchar(255)  NOT NULL,

    created_at     timestamp(6)  NOT NULL,
    created_by     varchar(100),
    updated_at     timestamp(6)  NOT NULL,
    updated_by     varchar(100),

    CONSTRAINT pk_training_program PRIMARY KEY (id),
    CONSTRAINT ck_training_program_status CHECK (status IN ('PLANNED', 'ONGOING', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE hrm_schema.training_session
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    training_program_id bigint       NOT NULL,
    session_date        timestamp(6) NOT NULL,
    location            varchar(255),
    trainer             varchar(255),
    capacity            integer      NOT NULL,
    status              varchar(255) NOT NULL,

    created_at          timestamp(6) NOT NULL,
    created_by          varchar(100),
    updated_at          timestamp(6) NOT NULL,
    updated_by          varchar(100),

    CONSTRAINT pk_training_session PRIMARY KEY (id),
    CONSTRAINT fk_training_session_program FOREIGN KEY (training_program_id) REFERENCES hrm_schema.training_program,
    CONSTRAINT ck_training_session_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX ix_training_session_program ON hrm_schema.training_session (training_program_id);

CREATE TABLE hrm_schema.training_enrollment
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id         bigint        NOT NULL,
    training_program_id bigint        NOT NULL,
    enrolled_date       date          NOT NULL,
    status              varchar(255)  NOT NULL,
    completion_date     date,
    score               numeric(5, 2),

    created_at          timestamp(6)  NOT NULL,
    created_by          varchar(100),
    updated_at          timestamp(6)  NOT NULL,
    updated_by          varchar(100),

    CONSTRAINT pk_training_enrollment PRIMARY KEY (id),
    CONSTRAINT uk_training_enrollment UNIQUE (employee_id, training_program_id),
    CONSTRAINT fk_training_enrollment_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_training_enrollment_program FOREIGN KEY (training_program_id) REFERENCES hrm_schema.training_program,
    CONSTRAINT ck_training_enrollment_status CHECK (status IN ('ENROLLED', 'COMPLETED', 'DROPPED'))
);

CREATE TABLE hrm_schema.certification
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id          bigint       NOT NULL,
    training_program_id  bigint,
    name                 varchar(255) NOT NULL,
    issuing_organization varchar(255) NOT NULL,
    issue_date           date         NOT NULL,
    expiry_date          date,
    certificate_url      varchar(255),

    created_at           timestamp(6) NOT NULL,
    created_by           varchar(100),
    updated_at           timestamp(6) NOT NULL,
    updated_by           varchar(100),

    CONSTRAINT pk_certification PRIMARY KEY (id),
    CONSTRAINT fk_certification_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_certification_program FOREIGN KEY (training_program_id) REFERENCES hrm_schema.training_program
);

CREATE INDEX ix_certification_employee ON hrm_schema.certification (employee_id);
