-- Separation: resignations, terminations and the exit clearance checklist.

CREATE TABLE hrm_schema.resignation
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id        bigint        NOT NULL,
    submitted_date     date          NOT NULL,
    last_working_date  date          NOT NULL,
    reason             varchar(1000) NOT NULL,
    notice_period_days integer       NOT NULL,
    status             varchar(255)  NOT NULL,
    approved_by_id     bigint,

    created_at         timestamp(6)  NOT NULL,
    created_by         varchar(100),
    updated_at         timestamp(6)  NOT NULL,
    updated_by         varchar(100),

    CONSTRAINT pk_resignation PRIMARY KEY (id),
    CONSTRAINT uk_resignation_employee UNIQUE (employee_id),
    CONSTRAINT fk_resignation_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_resignation_approver FOREIGN KEY (approved_by_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_resignation_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE hrm_schema.termination
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id      bigint        NOT NULL,
    termination_date date          NOT NULL,
    termination_type varchar(255)  NOT NULL,
    reason           varchar(1500) NOT NULL,
    initiated_by_id  bigint        NOT NULL,
    status           varchar(255)  NOT NULL,

    created_at       timestamp(6)  NOT NULL,
    created_by       varchar(100),
    updated_at       timestamp(6)  NOT NULL,
    updated_by       varchar(100),

    CONSTRAINT pk_termination PRIMARY KEY (id),
    CONSTRAINT uk_termination_employee UNIQUE (employee_id),
    CONSTRAINT fk_termination_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_termination_initiator FOREIGN KEY (initiated_by_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_termination_type CHECK (termination_type IN ('VOLUNTARY', 'INVOLUNTARY', 'LAYOFF')),
    CONSTRAINT ck_termination_status CHECK (status IN ('PENDING', 'FINALIZED'))
);

CREATE TABLE hrm_schema.clearance
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id    bigint       NOT NULL,
    department_id  bigint       NOT NULL,
    clearance_type varchar(255) NOT NULL,
    cleared_by_id  bigint,
    cleared_date   date,
    status         varchar(255) NOT NULL,
    remarks        varchar(255),

    created_at     timestamp(6) NOT NULL,
    created_by     varchar(100),
    updated_at     timestamp(6) NOT NULL,
    updated_by     varchar(100),

    CONSTRAINT pk_clearance PRIMARY KEY (id),
    CONSTRAINT uk_clearance_employee_department_type UNIQUE (employee_id, department_id, clearance_type),
    CONSTRAINT fk_clearance_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_clearance_department FOREIGN KEY (department_id) REFERENCES hrm_schema.department,
    CONSTRAINT fk_clearance_cleared_by FOREIGN KEY (cleared_by_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_clearance_type CHECK (clearance_type IN ('IT', 'FINANCE', 'ADMIN', 'FACILITIES')),
    CONSTRAINT ck_clearance_status CHECK (status IN ('PENDING', 'CLEARED'))
);
