-- Departments. The manager FK to employee is added in V3, once employee exists.

CREATE TABLE hrm_schema.department
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    description varchar(255),
    manager_id  bigint,

    created_at  timestamp(6) NOT NULL,
    created_by  varchar(100),
    updated_at  timestamp(6) NOT NULL,
    updated_by  varchar(100),

    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT uk_department_name UNIQUE (name),
    CONSTRAINT uk_department_manager UNIQUE (manager_id)
);
