-- Employee master data, plus the two FKs that close the department <-> employee cycle.

CREATE TABLE hrm_schema.employee
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_code  varchar(255) NOT NULL,
    first_name     varchar(255) NOT NULL,
    middle_name    varchar(255),
    last_name      varchar(255) NOT NULL,
    date_of_birth  date,
    gender         varchar(255) NOT NULL,
    national_id    varchar(255),
    nationality    varchar(255),
    marital_status varchar(255),
    email          varchar(255),
    phone          varchar(255),
    address        varchar(255),
    photo_url      varchar(255),
    job_title      varchar(255),
    department_id  bigint,
    salary         numeric(19, 4),
    status         varchar(255) NOT NULL,
    hire_date      date,

    created_at     timestamp(6) NOT NULL,
    created_by     varchar(100),
    updated_at     timestamp(6) NOT NULL,
    updated_by     varchar(100),

    CONSTRAINT pk_employee PRIMARY KEY (id),
    CONSTRAINT uk_employee_code UNIQUE (employee_code),
    CONSTRAINT uk_employee_email UNIQUE (email),
    CONSTRAINT ck_employee_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'TERMINATED'))
);

ALTER TABLE hrm_schema.employee
    ADD CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES hrm_schema.department;

ALTER TABLE hrm_schema.department
    ADD CONSTRAINT fk_department_manager FOREIGN KEY (manager_id) REFERENCES hrm_schema.employee;

CREATE INDEX ix_employee_department ON hrm_schema.employee (department_id);
