-- Organizational structure: legal entity -> branches, and job grades -> positions.
-- `job_position` rather than `position`, which is a SQL function name.

CREATE TABLE hrm_schema.organization
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    name                varchar(255) NOT NULL,
    legal_name          varchar(255),
    registration_number varchar(255),
    tax_id              varchar(255),
    industry            varchar(255),
    address             varchar(255),
    phone               varchar(255),
    email               varchar(255),
    website             varchar(255),
    logo_url            varchar(255),
    founded_date        date,

    created_at          timestamp(6) NOT NULL,
    created_by          varchar(100),
    updated_at          timestamp(6) NOT NULL,
    updated_by          varchar(100),

    CONSTRAINT pk_organization PRIMARY KEY (id)
);

CREATE TABLE hrm_schema.branch
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint       NOT NULL,
    name            varchar(255) NOT NULL,
    code            varchar(255) NOT NULL,
    address         varchar(255),
    city            varchar(255),
    region          varchar(255),
    country         varchar(255),
    phone           varchar(255),
    email           varchar(255),
    is_headquarters boolean      NOT NULL,
    status          varchar(255) NOT NULL,

    created_at      timestamp(6) NOT NULL,
    created_by      varchar(100),
    updated_at      timestamp(6) NOT NULL,
    updated_by      varchar(100),

    CONSTRAINT pk_branch PRIMARY KEY (id),
    CONSTRAINT uk_branch_code UNIQUE (code),
    CONSTRAINT fk_branch_organization FOREIGN KEY (organization_id) REFERENCES hrm_schema.organization,
    CONSTRAINT ck_branch_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_branch_organization ON hrm_schema.branch (organization_id);

CREATE TABLE hrm_schema.job_grade
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(255) NOT NULL,
    level       integer      NOT NULL,
    description varchar(255),
    min_salary  numeric(19, 4),
    max_salary  numeric(19, 4),

    created_at  timestamp(6) NOT NULL,
    created_by  varchar(100),
    updated_at  timestamp(6) NOT NULL,
    updated_by  varchar(100),

    CONSTRAINT pk_job_grade PRIMARY KEY (id),
    CONSTRAINT uk_job_grade_name UNIQUE (name)
);

CREATE TABLE hrm_schema.job_position
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    department_id bigint        NOT NULL,
    job_grade_id  bigint,
    title         varchar(255)  NOT NULL,
    code          varchar(255)  NOT NULL,
    description   varchar(1000),
    min_salary    numeric(19, 4),
    max_salary    numeric(19, 4),
    status        varchar(255)  NOT NULL,

    created_at    timestamp(6)  NOT NULL,
    created_by    varchar(100),
    updated_at    timestamp(6)  NOT NULL,
    updated_by    varchar(100),

    CONSTRAINT pk_job_position PRIMARY KEY (id),
    CONSTRAINT uk_job_position_code UNIQUE (code),
    CONSTRAINT fk_job_position_department FOREIGN KEY (department_id) REFERENCES hrm_schema.department,
    CONSTRAINT fk_job_position_job_grade FOREIGN KEY (job_grade_id) REFERENCES hrm_schema.job_grade,
    CONSTRAINT ck_job_position_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_job_position_department ON hrm_schema.job_position (department_id);
