-- Per-employee records: documents, contracts, and the position/department change log.

CREATE TABLE hrm_schema.employee_document
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id   bigint       NOT NULL,
    document_type varchar(255) NOT NULL,
    file_name     varchar(255) NOT NULL,
    file_url      varchar(255) NOT NULL,
    uploaded_at   timestamp(6) NOT NULL,
    expiry_date   date,
    verified      boolean      NOT NULL,

    created_at    timestamp(6) NOT NULL,
    created_by    varchar(100),
    updated_at    timestamp(6) NOT NULL,
    updated_by    varchar(100),

    CONSTRAINT pk_employee_document PRIMARY KEY (id),
    CONSTRAINT fk_employee_document_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_employee_document_type CHECK (document_type IN ('CV', 'ID', 'CERTIFICATE', 'CONTRACT', 'OTHER'))
);

CREATE INDEX ix_employee_document_employee ON hrm_schema.employee_document (employee_id);

CREATE TABLE hrm_schema.employment_contract
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id         bigint         NOT NULL,
    contract_type       varchar(255)   NOT NULL,
    start_date          date           NOT NULL,
    end_date            date,
    salary              numeric(19, 4) NOT NULL,
    currency            varchar(10)    NOT NULL,
    work_hours_per_week integer        NOT NULL,
    status              varchar(255)   NOT NULL,
    signed_date         date,
    document_url        varchar(255),

    created_at          timestamp(6)   NOT NULL,
    created_by          varchar(100),
    updated_at          timestamp(6)   NOT NULL,
    updated_by          varchar(100),

    CONSTRAINT pk_employment_contract PRIMARY KEY (id),
    CONSTRAINT fk_employment_contract_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_employment_contract_type CHECK (contract_type IN ('PERMANENT', 'TEMPORARY', 'INTERN', 'CONTRACT')),
    CONSTRAINT ck_employment_contract_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'TERMINATED'))
);

CREATE INDEX ix_employment_contract_employee ON hrm_schema.employment_contract (employee_id);

CREATE TABLE hrm_schema.employment_history
(
    id                     bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id            bigint       NOT NULL,
    previous_position_id   bigint,
    new_position_id        bigint       NOT NULL,
    previous_department_id bigint,
    new_department_id      bigint       NOT NULL,
    change_type            varchar(255) NOT NULL,
    effective_date         date         NOT NULL,
    reason                 varchar(255),
    approved_by_id         bigint       NOT NULL,

    created_at             timestamp(6) NOT NULL,
    created_by             varchar(100),
    updated_at             timestamp(6) NOT NULL,
    updated_by             varchar(100),

    CONSTRAINT pk_employment_history PRIMARY KEY (id),
    CONSTRAINT fk_employment_history_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_employment_history_approver FOREIGN KEY (approved_by_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_employment_history_prev_position FOREIGN KEY (previous_position_id) REFERENCES hrm_schema.job_position,
    CONSTRAINT fk_employment_history_new_position FOREIGN KEY (new_position_id) REFERENCES hrm_schema.job_position,
    CONSTRAINT fk_employment_history_prev_department FOREIGN KEY (previous_department_id) REFERENCES hrm_schema.department,
    CONSTRAINT fk_employment_history_new_department FOREIGN KEY (new_department_id) REFERENCES hrm_schema.department,
    CONSTRAINT ck_employment_history_change_type
        CHECK (change_type IN ('PROMOTION', 'TRANSFER', 'DEMOTION', 'SALARY_CHANGE'))
);

CREATE INDEX ix_employment_history_employee ON hrm_schema.employment_history (employee_id);
