-- Attendance: shifts and work schedules, the daily record, and overtime requests.

CREATE TABLE hrm_schema.shift
(
    id                      bigint GENERATED BY DEFAULT AS IDENTITY,
    name                    varchar(255) NOT NULL,
    start_time              time(0)      NOT NULL,
    end_time                time(0)      NOT NULL,
    break_duration_minutes  integer      NOT NULL,
    grace_period_minutes    integer      NOT NULL,
    status                  varchar(255) NOT NULL,

    created_at              timestamp(6) NOT NULL,
    created_by              varchar(100),
    updated_at              timestamp(6) NOT NULL,
    updated_by              varchar(100),

    CONSTRAINT pk_shift PRIMARY KEY (id),
    CONSTRAINT uk_shift_name UNIQUE (name),
    CONSTRAINT ck_shift_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE hrm_schema.work_schedule
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id    bigint       NOT NULL,
    shift_id       bigint       NOT NULL,
    effective_date date         NOT NULL,
    end_date       date,
    status         varchar(255) NOT NULL,

    created_at     timestamp(6) NOT NULL,
    created_by     varchar(100),
    updated_at     timestamp(6) NOT NULL,
    updated_by     varchar(100),

    CONSTRAINT pk_work_schedule PRIMARY KEY (id),
    CONSTRAINT fk_work_schedule_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_work_schedule_shift FOREIGN KEY (shift_id) REFERENCES hrm_schema.shift,
    CONSTRAINT ck_work_schedule_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_work_schedule_employee ON hrm_schema.work_schedule (employee_id);

-- Which weekdays a schedule covers (@ElementCollection on WorkSchedule.daysOfWeek).
CREATE TABLE hrm_schema.work_schedule_day
(
    work_schedule_id bigint NOT NULL,
    day_of_week      varchar(255),

    CONSTRAINT uk_work_schedule_day UNIQUE (work_schedule_id, day_of_week),
    CONSTRAINT fk_work_schedule_day_schedule FOREIGN KEY (work_schedule_id) REFERENCES hrm_schema.work_schedule,
    CONSTRAINT ck_work_schedule_day_of_week CHECK (day_of_week IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE TABLE hrm_schema.attendance
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id    bigint       NOT NULL,
    date           date         NOT NULL,
    check_in_time  time(0),
    check_out_time time(0),
    status         varchar(255) NOT NULL,

    created_at     timestamp(6) NOT NULL,
    created_by     varchar(100),
    updated_at     timestamp(6) NOT NULL,
    updated_by     varchar(100),

    CONSTRAINT pk_attendance PRIMARY KEY (id),
    -- one record per employee per day; AttendanceService checks this first
    CONSTRAINT uk_attendance_employee_date UNIQUE (employee_id, date),
    CONSTRAINT fk_attendance_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_attendance_status CHECK (status IN ('PRESENT', 'ABSENT', 'ON_LEAVE'))
);

CREATE TABLE hrm_schema.overtime_request
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id     bigint        NOT NULL,
    request_date    date          NOT NULL,
    start_time      time(0)       NOT NULL,
    end_time        time(0)       NOT NULL,
    hours           numeric(4, 2) NOT NULL,
    reason          varchar(255)  NOT NULL,
    status          varchar(255)  NOT NULL,
    approved_by_id  bigint,
    rate_multiplier numeric(3, 2),

    created_at      timestamp(6)  NOT NULL,
    created_by      varchar(100),
    updated_at      timestamp(6)  NOT NULL,
    updated_by      varchar(100),

    CONSTRAINT pk_overtime_request PRIMARY KEY (id),
    CONSTRAINT fk_overtime_request_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT fk_overtime_request_approver FOREIGN KEY (approved_by_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_overtime_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX ix_overtime_request_employee ON hrm_schema.overtime_request (employee_id);
