-- Leave requests and their approval state.

CREATE TABLE hrm_schema.leave_request
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id bigint       NOT NULL,
    leave_type  varchar(255) NOT NULL,
    reason      varchar(255),
    status      varchar(255) NOT NULL,
    start_date  date         NOT NULL,
    end_date    date         NOT NULL,

    created_at  timestamp(6) NOT NULL,
    created_by  varchar(100),
    updated_at  timestamp(6) NOT NULL,
    updated_by  varchar(100),

    CONSTRAINT pk_leave_request PRIMARY KEY (id),
    CONSTRAINT fk_leave_request_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_leave_request_type
        CHECK (leave_type IN ('SICK', 'CASUAL', 'ANNUAL', 'UNPAID', 'MATERNITY', 'PATERNITY')),
    CONSTRAINT ck_leave_request_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

-- LeaveRepository.findOverlappingLeaves filters by employee + status + date range.
CREATE INDEX ix_leave_request_employee_status ON hrm_schema.leave_request (employee_id, status);
