-- Payroll source data owned by HR. FMS turns it into the salary-expense journal off
-- the PayrollProcessed event — HRM stores no accounting entries (blueprint §1, §8).

CREATE TABLE hrm_schema.payroll
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_id      bigint         NOT NULL,
    pay_period_start date           NOT NULL,
    pay_period_end   date           NOT NULL,
    basic_salary     numeric(19, 4) NOT NULL,
    allowances       numeric(19, 4),
    deductions       numeric(19, 4),
    net_salary       numeric(19, 4) NOT NULL,
    status           varchar(255)   NOT NULL,
    payment_date     date,

    created_at       timestamp(6)   NOT NULL,
    created_by       varchar(100),
    updated_at       timestamp(6)   NOT NULL,
    updated_by       varchar(100),

    CONSTRAINT pk_payroll PRIMARY KEY (id),
    CONSTRAINT fk_payroll_employee FOREIGN KEY (employee_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_payroll_status CHECK (status IN ('PENDING', 'PAID', 'CANCELLED'))
);

CREATE INDEX ix_payroll_employee ON hrm_schema.payroll (employee_id);
CREATE INDEX ix_payroll_period ON hrm_schema.payroll (pay_period_start);
