-- Recruitment: candidates, vacancies, applications and interviews.

CREATE TABLE hrm_schema.candidate
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    first_name       varchar(255) NOT NULL,
    last_name        varchar(255) NOT NULL,
    email            varchar(255) NOT NULL,
    phone            varchar(255),
    resume_url       varchar(255),
    cover_letter_url varchar(255),
    linkedin_url     varchar(255),
    source           varchar(255),
    status           varchar(255) NOT NULL,

    created_at       timestamp(6) NOT NULL,
    created_by       varchar(100),
    updated_at       timestamp(6) NOT NULL,
    updated_by       varchar(100),

    CONSTRAINT pk_candidate PRIMARY KEY (id),
    CONSTRAINT uk_candidate_email UNIQUE (email),
    CONSTRAINT ck_candidate_source CHECK (source IN ('REFERRAL', 'JOB_BOARD', 'WEBSITE', 'AGENCY')),
    CONSTRAINT ck_candidate_status CHECK (status IN ('NEW', 'IN_PROCESS', 'HIRED', 'REJECTED'))
);

CREATE TABLE hrm_schema.job_posting
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    position_id        bigint        NOT NULL,
    department_id      bigint        NOT NULL,
    title              varchar(255)  NOT NULL,
    description        varchar(2000) NOT NULL,
    requirements       varchar(2000),
    employment_type    varchar(255)  NOT NULL,
    number_of_openings integer       NOT NULL,
    posted_date        date          NOT NULL,
    closing_date       date          NOT NULL,
    status             varchar(255)  NOT NULL,
    -- the hiring employee behind the posting; created_by below is the acting user
    created_by_id      bigint        NOT NULL,

    created_at         timestamp(6)  NOT NULL,
    created_by         varchar(100),
    updated_at         timestamp(6)  NOT NULL,
    updated_by         varchar(100),

    CONSTRAINT pk_job_posting PRIMARY KEY (id),
    CONSTRAINT fk_job_posting_position FOREIGN KEY (position_id) REFERENCES hrm_schema.job_position,
    CONSTRAINT fk_job_posting_department FOREIGN KEY (department_id) REFERENCES hrm_schema.department,
    CONSTRAINT fk_job_posting_created_by FOREIGN KEY (created_by_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_job_posting_employment_type
        CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN')),
    CONSTRAINT ck_job_posting_status CHECK (status IN ('OPEN', 'CLOSED', 'DRAFT'))
);

CREATE INDEX ix_job_posting_department_status ON hrm_schema.job_posting (department_id, status);

CREATE TABLE hrm_schema.job_application
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    candidate_id   bigint        NOT NULL,
    job_posting_id bigint        NOT NULL,
    applied_date   date          NOT NULL,
    status         varchar(255)  NOT NULL,
    cover_letter   varchar(3000),
    resume_url     varchar(255),
    notes          varchar(255),

    created_at     timestamp(6)  NOT NULL,
    created_by     varchar(100),
    updated_at     timestamp(6)  NOT NULL,
    updated_by     varchar(100),

    CONSTRAINT pk_job_application PRIMARY KEY (id),
    CONSTRAINT fk_job_application_candidate FOREIGN KEY (candidate_id) REFERENCES hrm_schema.candidate,
    CONSTRAINT fk_job_application_posting FOREIGN KEY (job_posting_id) REFERENCES hrm_schema.job_posting,
    CONSTRAINT ck_job_application_status
        CHECK (status IN ('APPLIED', 'SHORTLISTED', 'INTERVIEW', 'OFFERED', 'REJECTED', 'HIRED'))
);

CREATE INDEX ix_job_application_posting ON hrm_schema.job_application (job_posting_id);
CREATE INDEX ix_job_application_candidate ON hrm_schema.job_application (candidate_id);

CREATE TABLE hrm_schema.interview
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    job_application_id bigint       NOT NULL,
    interviewer_id     bigint       NOT NULL,
    scheduled_date     timestamp(6) NOT NULL,
    mode               varchar(255) NOT NULL,
    location           varchar(255),
    status             varchar(255) NOT NULL,
    feedback           varchar(255),
    rating             integer      NOT NULL,

    created_at         timestamp(6) NOT NULL,
    created_by         varchar(100),
    updated_at         timestamp(6) NOT NULL,
    updated_by         varchar(100),

    CONSTRAINT pk_interview PRIMARY KEY (id),
    CONSTRAINT fk_interview_application FOREIGN KEY (job_application_id) REFERENCES hrm_schema.job_application,
    CONSTRAINT fk_interview_interviewer FOREIGN KEY (interviewer_id) REFERENCES hrm_schema.employee,
    CONSTRAINT ck_interview_mode CHECK (mode IN ('ONSITE', 'VIRTUAL', 'PHONE')),
    CONSTRAINT ck_interview_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX ix_interview_application ON hrm_schema.interview (job_application_id);
CREATE INDEX ix_interview_interviewer ON hrm_schema.interview (interviewer_id);
