CREATE TABLE warehouses (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    location VARCHAR(255) NOT NULL,
    warehouse_type VARCHAR(50) NOT NULL,
    capacity NUMERIC(15, 2) NOT NULL CHECK (capacity > 0),
    manager_name VARCHAR(200),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE materials (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    unit_of_measure VARCHAR(30) NOT NULL,
    unit_cost NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
    reorder_level NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id VARCHAR(50) NOT NULL REFERENCES materials(id),
    warehouse_id VARCHAR(50) NOT NULL REFERENCES warehouses(id),
    on_hand NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (on_hand >= 0),
    reserved NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (reserved >= 0),
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_material_warehouse UNIQUE (material_id, warehouse_id),
    CONSTRAINT ck_inventory_reserved CHECK (reserved <= on_hand)
);

CREATE TABLE stock_movements (
    id VARCHAR(50) PRIMARY KEY,
    movement_type VARCHAR(20) NOT NULL,
    material_id VARCHAR(50) NOT NULL REFERENCES materials(id),
    warehouse_id VARCHAR(50) NOT NULL REFERENCES warehouses(id),
    quantity NUMERIC(15, 2) NOT NULL,
    reference_number VARCHAR(100) NOT NULL,
    notes VARCHAR(500),
    processed_by VARCHAR(100) NOT NULL,
    movement_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE goods_receipts (
    id VARCHAR(50) PRIMARY KEY,
    purchase_order_reference VARCHAR(100) NOT NULL,
    warehouse_id VARCHAR(50) NOT NULL REFERENCES warehouses(id),
    receipt_date DATE NOT NULL,
    received_by VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    notes VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE requisitions (
    id VARCHAR(50) PRIMARY KEY,
    requested_by VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    material_id VARCHAR(50) NOT NULL REFERENCES materials(id),
    quantity NUMERIC(15, 2) NOT NULL CHECK (quantity > 0),
    required_date DATE NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_inventory_warehouse ON inventory(warehouse_id);
CREATE INDEX idx_inventory_material ON inventory(material_id);
CREATE INDEX idx_movements_material_date ON stock_movements(material_id, movement_date);
CREATE INDEX idx_requisitions_status ON requisitions(status);
