CREATE TABLE goods_receipt_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_receipt_id VARCHAR(50) NOT NULL REFERENCES goods_receipts(id) ON DELETE CASCADE,
    material_id VARCHAR(50) NOT NULL REFERENCES materials(id),
    quantity NUMERIC(15, 2) NOT NULL CHECK (quantity > 0),
    unit_cost NUMERIC(15, 2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0)
);

CREATE INDEX idx_goods_receipt_lines_receipt ON goods_receipt_lines(goods_receipt_id);
CREATE INDEX idx_goods_receipt_lines_material ON goods_receipt_lines(material_id);
